language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer update --prefer-stable --prefer-source
  - tests/bin/extenderd -d -s

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
  - killall php
